name: Build Hello World
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: javac helloWorldApp.java
      - run: java helloWorldApp